# Generated by Django 5.2.3 on 2025-06-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_telegramuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='phone_no',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='user_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
