# Generated by Django 5.2.3 on 2025-06-19 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_telegramuser_phone_no_telegramuser_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='user_id',
        ),
    ]
